# Generated by Django 3.0.7 on 2020-06-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('profile_pic', models.ImageField(default='/images/default/image.jpeg', upload_to='images')),
                ('email_address', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=100)),
                ('subject', models.TextField(max_length=500)),
            ],
        ),
    ]
